Numpy 

In [1]:
import numpy as np

a = np.array([1,2,3])
print('type : ',type(a))
print(a)

type :  <class 'numpy.ndarray'>
[1 2 3]


In [2]:
import numpy as np

b = np.array([[1, 2, 3],[4, 5, 6]])
print('b:', b)
print('b transport:', b.T)

b: [[1 2 3]
 [4 5 6]]
b transport: [[1 4]
 [2 5]
 [3 6]]


ndarry: axis & dimension

In [3]:
import numpy as np

A1 = np.array([1, 2, 3])
print('A1 type : ',type(A1))
print('A1 shape: ', A1.shape)
print('A1 axis: ', A1.ndim)
print('A1 :',A1)

A1 type :  <class 'numpy.ndarray'>
A1 shape:  (3,)
A1 axis:  1
A1 : [1 2 3]


In [4]:
A2 = np.array([[1, 2, 3],[4, 5, 6]])
print('A2 shape: ', A2.shape)
print('A2 axis: ', A2.ndim)
print('A2 :',A2)

A2 shape:  (2, 3)
A2 axis:  2
A2 : [[1 2 3]
 [4 5 6]]


In [5]:
A3 = np.array([A2,A2])
print('A3 shape: ', A3.shape)
print('A3 axis: ', A3.ndim)
print('A3 :',A3)

A3 shape:  (2, 2, 3)
A3 axis:  3
A3 : [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


把axis作為input

In [6]:
A3.sum(axis=0)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
A3.sum(axis=1)

array([[5, 7, 9],
       [5, 7, 9]])

In [8]:
A3.sum(axis=2)

array([[ 6, 15],
       [ 6, 15]])

ndarry : 1 axis 的切片 (1) [start : stop] (2) [start:stop:step]

In [9]:
import numpy as np

V1 = np.arange(10)
print('V1 [1:5] :', V1[1:5])
print('V1[0:8:2]:',V1[0:8:2])
print('V1[::-2]:',V1[::-2])

V1 [1:5] : [1 2 3 4]
V1[0:8:2]: [0 2 4 6]
V1[::-2]: [9 7 5 3 1]


ndarry : 2 axis 的切片  [axis0切片, axis1切片, ...]

In [10]:
import numpy as np

A4 = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('A4 shape: ', A4.shape)
print('A4 axis: ', A4.ndim)
print('A4 :',A4)

A4 shape:  (4, 3)
A4 axis:  2
A4 : [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
A4[1:4,0:2]

array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [12]:
A4[::2,:]

array([[0, 1, 2],
       [6, 7, 8]])

In [13]:
A4[::-1,::-1]

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

陣列擴張 (brodscasting)
規則1: 2個陣列axis不同時，axis較少的會加入新的axis，在shape左邊補1

In [14]:
import numpy as np

arr1 = np.array([[1,2]])
arr2 = np.array([3,4])
print('arr1 axis:', arr1.ndim)
print('arr1 shape:', arr1.shape)
print('arr1:',arr1)
print('arr2 axis:', arr2.ndim)
print('arr2 shape:', arr2.shape)
print('arr2:',arr2)

arr1 axis: 2
arr1 shape: (1, 2)
arr1: [[1 2]]
arr2 axis: 1
arr2 shape: (2,)
arr2: [3 4]


In [15]:
arr1+arr2 # arr2 擴張為2軸

array([[4, 6]])

規則2: 2個陣列axis相同時，會比各axis的維度，若維度不同時，
(2-1)維度為1的會擴張和另一相配
(2-2)若皆不是1維，則無法擴張，回傳錯誤

In [16]:
#(2-1)維度為1的會擴張和另一相配
import numpy as np

arr1 = np.array([1,2])
arr2 = np.array([[3,4],[5,6]])
print('arr1 shape:', arr1.shape)
print('arr2 shape:', arr2.shape)
arr12 = arr1 + arr2
print('arr1 + arr2 shape:', arr12.shape)
print('arr1 + arr2: ', arr12)

arr1 shape: (2,)
arr2 shape: (2, 2)
arr1 + arr2 shape: (2, 2)
arr1 + arr2:  [[4 6]
 [6 8]]


In [17]:
#(2-2)若皆不是1維，則無法擴張，回傳錯誤
import numpy as np

arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('arr3 shape:', arr3.shape)
print('arr4 shape:', arr4.shape)
arr3+arr4

arr3 shape: (2, 2)
arr4 shape: (3, 3)


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

陣列重塑 reshape() resize()

In [18]:
import numpy as np

arr1 = np.arange(12)
print('arr1 shape:', arr1.shape)
print('arr1 :', arr1)

arr2 = np.reshape(arr1,(3,4))
print('arr2 shape:', arr2.shape)
print('arr2 :', arr2)

arr2[0,1] = 0
print('arr2 :', arr2)
print('arr1 :', arr1)


arr1 shape: (12,)
arr1 : [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr2 shape: (3, 4)
arr2 : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr2 : [[ 0  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr1 : [ 0  0  2  3  4  5  6  7  8  9 10 11]


In [19]:
import numpy as np

arr1 = np.arange(12)
print('arr1 shape:', arr1.shape)
print('arr1 :', arr1)

arr2 = np.reshape(arr1,(2,-1))
print('arr2 shape:', arr2.shape)
print('arr2 :', arr2)

arr1 shape: (12,)
arr1 : [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr2 shape: (2, 6)
arr2 : [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [20]:
np.reshape(arr1,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

C & Fortran order

In [21]:
import numpy as np

arr3 = np.arange(12)
print('arr3 shape:', arr3.shape)
print('arr3 :', arr3)

arr3_c = np.reshape(arr3,(3,4),order='C')
print('arr3_c shape:', arr3_c.shape)
print('arr3_c :', arr3_c)

arr3_f = np.reshape(arr3,(3,4),order='F')
print('arr3_f shape:', arr3_f.shape)
print('arr3_f :', arr3_f)

arr3 shape: (12,)
arr3 : [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr3_c shape: (3, 4)
arr3_c : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr3_f shape: (3, 4)
arr3_f : [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [22]:
arr3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

np.resize()

In [23]:
import numpy as np

arr1 = np.arange(12)
print('arr1 shape:', arr1.shape)
print('arr1 :', arr1)

arr2 = np.resize(arr1,(3,4))
print('arr2 shape:', arr2.shape)
print('arr2 :', arr2)


arr1 shape: (12,)
arr1 : [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr2 shape: (3, 4)
arr2 : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
# size 不符時
arr3 = np.resize(arr1,(3,5)) #不足從頭覆寫
print('arr3 shape:', arr3.shape)
print('arr3 :', arr3)

arr4 = np.resize(arr1,(3,2)) #太多時，只取需要的部份
print('arr4 shape:', arr4.shape)
print('arr4 :', arr4)

arr3 shape: (3, 5)
arr3 : [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]]
arr4 shape: (3, 2)
arr4 : [[0 1]
 [2 3]
 [4 5]]


In [25]:
arr5 = np.resize(arr1,(4,3))
print('arr5 shape:', arr5.shape)
print('arr5 :', arr5)

#resize後回傳的新物件
arr5[0,1]=0
print('arr5 :', arr5)
print('arr1 :', arr1)

arr5 shape: (4, 3)
arr5 : [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr5 : [[ 0  0  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr1 : [ 0  1  2  3  4  5  6  7  8  9 10 11]


陣列的存&讀

In [26]:
import numpy as np

file_nam = '/Users/rick/Desktop/arr1'

arr1 = np.random.randint(10,size=(5,4))
print('arr1 create:',arr1)
print('arr1 shape:',arr1.shape)
np.save(file_nam,arr1)

arr1 create: [[6 1 1 0]
 [0 9 1 2]
 [9 1 7 0]
 [3 5 4 5]
 [8 6 7 8]]
arr1 shape: (5, 4)


FileNotFoundError: [Errno 2] No such file or directory: '/Users/rick/Desktop/arr1.npy'

In [27]:
import numpy as np

file_nam = '/Users/rick/Desktop/arr1.npy'
arr2 = np.load(file_nam)
print('arr2 create:',arr2)
print('arr2 shape:',arr2.shape)


FileNotFoundError: [Errno 2] No such file or directory: '/Users/rick/Desktop/arr1.npy'

以文字方式存&讀陣列

In [28]:
import numpy as np

goal_dir = '/Users/rick/Desktop/'
arr1 = np.random.randn(3,4)
print('arr1 save:',arr1)
print('arr1 shape:',arr1.shape)
np.savetxt(goal_dir+'arr1.txt', arr1)

# read
arr1_txt = np.loadtxt(goal_dir+'arr1.txt')

print('arr1 load:',arr1_txt)
print('arr1 shape:',arr1_txt.shape)

arr1 save: [[-0.67169778  0.92322773  0.19609021 -0.8068889 ]
 [-0.24029513 -2.81346983 -0.82823414  1.82870582]
 [ 2.48316448 -1.10942875  0.73304636 -0.23259575]]
arr1 shape: (3, 4)


FileNotFoundError: [Errno 2] No such file or directory: '/Users/rick/Desktop/arr1.txt'

In [29]:
import numpy as np

goal_dir = '/Users/rick/Desktop/'
arr2 = np.random.randn(5,3)
print('arr2 save:',arr2)
print('arr2 shape:',arr2.shape)
np.savetxt(goal_dir+'arr2.csv', arr2)

# read
arr2_csv = np.loadtxt(goal_dir+'arr2.csv')

print('arr2 load:',arr2_csv)
print('arr2 shape:',arr2_csv.shape)

arr2 save: [[-0.03311961 -0.38538583 -1.08747513]
 [ 1.93982989  0.97662948  1.15032665]
 [-2.44643803  0.33162165 -0.93485517]
 [ 1.49664737  0.84872168  0.16046191]
 [-0.89878359 -1.37827758 -0.81198956]]
arr2 shape: (5, 3)


FileNotFoundError: [Errno 2] No such file or directory: '/Users/rick/Desktop/arr2.csv'

In [30]:
#delimiter
import numpy as np

goal_dir = '/Users/rick/Desktop/'
arr3 = np.random.randn(4,2)
print('arr3 save:',arr3)
print('arr3 shape:',arr3.shape)
np.savetxt(goal_dir+'arr3.txt', arr3, delimiter=',')

# read
#arr3_txt = np.loadtxt(goal_dir+'arr3.txt')
arr3_txt = np.loadtxt(goal_dir+'arr3.txt',delimiter=',')

print('arr3 load:',arr3_txt)
print('arr3 shape:',arr3_txt.shape)

arr3 save: [[-2.11074369  0.50100064]
 [ 0.76475175  1.71912133]
 [ 0.79151165 -0.20107826]
 [ 1.20578446 -1.37342752]]
arr3 shape: (4, 2)


FileNotFoundError: [Errno 2] No such file or directory: '/Users/rick/Desktop/arr3.txt'

In [31]:
#fmt : detault %.18e
import numpy as np

goal_dir = '/Users/rick/Desktop/'
arr4 = np.random.randn(4,4)
print('arr4 save:',arr4)
print('arr4 shape:',arr4.shape)
np.savetxt(goal_dir+'arr4_e.txt', arr4, fmt ='%.4e')
np.savetxt(goal_dir+'arr4_f.txt', arr4, fmt ='%.4f')

arr4 save: [[-0.19557107  0.43894367  0.87733325 -0.66863017]
 [-0.40353799 -0.10417886 -1.21487783  0.73694254]
 [-0.31757242  1.06021011  1.02565214  0.72483362]
 [ 0.83897732 -1.35104169  0.0401468  -0.06302585]]
arr4 shape: (4, 4)


FileNotFoundError: [Errno 2] No such file or directory: '/Users/rick/Desktop/arr4_e.txt'

In [32]:
# header, footer, comments
import numpy as np
goal_dir = '/Users/rick/Desktop/'
arr5 = np.random.randn(4,4)
print('arr5 save:',arr5)
print('arr5 shape:',arr5.shape)
np.savetxt(goal_dir+'arr5_1.txt', arr5, fmt ='%.4e',\
    header='header line', footer='footer line')

np.savetxt(goal_dir+'arr5_2.txt', arr5, fmt ='%.4e',\
    header='header line', footer='footer line',\
    comments='>>>')

#arr5_1 = np.loadtxt(goal_dir+'arr5_2.txt')
arr5_1 = np.loadtxt(goal_dir+'arr5_2.txt',comments='>>>')
print('arr5 load:',arr5_1)
print('arr5 shape:',arr5_1.shape)


arr5 save: [[ 0.43397203  1.6043776  -0.01036251 -0.35794163]
 [ 0.16337266  0.33771187 -0.12093796 -0.78543735]
 [ 1.03484371 -2.19121159  0.22581422  1.15329832]
 [ 0.16250765  1.10941752  0.45486289  1.09024927]]
arr5 shape: (4, 4)


FileNotFoundError: [Errno 2] No such file or directory: '/Users/rick/Desktop/arr5_1.txt'

In [ ]:
# usecols & skiprows
import numpy as np

goal_dir = '/Users/rick/Desktop/'
arr6 = np.random.randn(5,5)
print('arr6 save:',arr6)
print('arr6 shape:',arr6.shape)
np.savetxt(goal_dir+'arr6.txt', arr6,)

arr6_1 = np.loadtxt(goal_dir+'arr6.txt',usecols=(0,2))
print('arr6 usecols=(0,2) load:',arr6_1)
print('arr6_1 shape:',arr6_1.shape)

arr6_2 = np.loadtxt(goal_dir+'arr6.txt',usecols=(0,2,4))
print('arr6 usecols=(0,2,4) load:',arr6_2)
print('arr6_2 shape:',arr6_2.shape)

In [33]:
# skiprows : 忽略開頭前幾行
arr6_3 = np.loadtxt(goal_dir+'arr6.txt',skiprows=1)
print('arr6 skiprows=1 load:',arr6_3)
print('arr6_3 shape:',arr6_3.shape)

arr6_4 = np.loadtxt(goal_dir+'arr6.txt',skiprows=2)
print('arr6 skiprows=2 load:',arr6_4)
print('arr6_4 shape:',arr6_4.shape)

OSError: /Users/rick/Desktop/arr6.txt not found.

讀文字

In [ ]:
#指定資料類別 dtype
import numpy as np
test_file = '/Users/rick/Desktop/test_file.txt'
# name age gender tall major 
#Amy  20  F 165.7  ES
#
np.loadtxt(test_file,dtype=[('col1','S10'),('col2','i8'),\
    ('col3','S10'),('col4','f8'),('col5','S10')])

In [ ]:
#unpack
np.loadtxt(test_file,dtype=[('col1','S10'),('col2','i8'),\
    ('col3','S10'),('col4','f8'),('col5','S10')],unpack=True)

In [ ]:
name,age,gender,tall,major = np.loadtxt(test_file,dtype=[('col1','S10'),('col2','i8'),\
    ('col3','S10'),('col4','f8'),('col5','S10')],unpack=True)
print('name:',name)
print('age:',age)
print('gender:',gender)
print('tall:',tall)
print('major:',major)

some method functions

In [34]:
import numpy as np
test_file = '/Users/rick/Desktop/test_file.txt'
# name age gender tall major 
#Amy  20  F 165.7  ES
name,age,gender,tall,major = np.loadtxt(test_file,dtype=[('col1','S10'),('col2','i8'),\
    ('col3','S10'),('col4','f8'),('col5','S10')],unpack=True)
print('name:',name)
print('age:',age)
print('gender:',gender)
print('tall:',tall)
print('major:',major)

print('age mean:',np.mean(age))
print('age median:',np.median(age))
print('tall mean:',np.mean(tall))
print('tall median:',np.median(tall))

OSError: /Users/rick/Desktop/test_file.txt not found.